kind: pipeline
type: docker
name: default

steps:
- name: build-and-push-image
  image: plugins/docker
  settings:
    mtu: 1450
    registry: git.stropus.dev
    username: 
      from_secret: GITEA_USER
    password:
      from_secret: GITEA_TOKEN
    repo: git.stropus.dev/tomas/discord-strava
    tags: 0.0.1
    dockerfile: ./Dockerfile # Where the Dockerfile is located in your git repository
  when:
    branch:
    - master
    event:
    - push