kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  environment:
    GITEA_TOKEN:
      from_secret: GITEA_TOKEN
- name: build-and-push-image
  image: plugins/docker
  settings:
    mtu: 1450
  # volumes:
  # - name: dockersock
  #   path: "/var/run/docker.sock" # Mandatory
  settings:
    registry: git.stropus.dev
    username: tomas
    password:
      from_secret: GITEA_TOKEN
    repo: tomas/discord-strava
    tags: 0.0.1
    dockerfile: ./Dockerfile # Where the Dockerfile is located in your git repository