kind: pipeline
type: docker
name: deploy

steps:
- name: build-and-push-image
  image: plugins/docker
  settings:
    mtu: 1450
    registry: git.stropus.dev
    username: 
      from_secret: GITEA_USER
    password:
      from_secret: GITEA_TOKEN
    repo: git.stropus.dev/tomas/discord-strava
    tags: ${DRONE_TAG}
    dockerfile: ./Dockerfile

trigger:
  event:
  - tag