version: "3.8"

services:

  ds_db:
    image: postgres:15
    container_name: ds_db
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped