CREATE TABLE IF NOT EXISTS athlete_activity (
  id SERIAL PRIMARY KEY,
  athlete_id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  start_date TEXT NOT NULL,
  utc_offset INT NOT NULL,
  type TEXT NOT NULL,
  distance REAL,
  moving_time INT,
  elapsed_time INT,
  elev_high REAL,
  elev_low REAL,
  total_elevation_gain INT,
  average_speed REAL,
  max_speed REAL,
  average_cadence REAL,
  has_heartrate BOOLEAN,
  average_heartrate REAL,
  max_heartrate REAL,
  kilojoules REAL,
  achievement_count INT
);