CREATE TABLE IF NOT EXISTS athlete_activity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  athlete_id INTEGER NOT NULL,
  activity_id INTEGER NOT NULL,
  start_date TEXT NOT NULL,
  utc_offset INTEGER NOT NULL,
  type TEXT NOT NULL,
  distance REAL,
  moving_time INTEGER,
  elapsed_time INTEGER,
  elev_high REAL,
  elev_low REAL,
  total_elevation_gain INTEGER,
  average_speed REAL,
  max_speed REAL,
  average_cadence REAL,
  has_heartrate BOOLEAN,
  average_heartrate REAL,
  max_heartrate REAL,
  kilojoules REAL,
  achievement_count INTEGER
);