CREATE TABLE IF NOT EXISTS athlete_activity (
  id SERIAL PRIMARY KEY,
  athlete_id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  start_date TEXT NOT NULL,
  utc_offset INT NOT NULL,
  type TEXT NOT NULL,
  distance DECIMAL(12,4),
  moving_time INT,
  elapsed_time INT,
  elev_high DECIMAL(12,4),
  elev_low DECIMAL(12,4),
  total_elevation_gain INT,
  average_speed DECIMAL(12,4),
  max_speed DECIMAL(12,4),
  average_cadence DECIMAL(12,4),
  has_heartrate BOOLEAN,
  average_heartrate DECIMAL(12,4),
  max_heartrate DECIMAL(12,4),
  kilojoules DECIMAL(12,4),
  achievement_count INT
);